-- 코드를 입력하세요
SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, ROUND(AVG(RE.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO INFO JOIN REST_REVIEW RE
ON INFO.REST_ID = RE.REST_ID
GROUP BY RE.REST_ID
HAVING INFO.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;