-- 코드를 작성해주세요
-- 코드를 작성해주세요
SELECT YEAR(ED.DIFFERENTIATION_DATE) YEAR,
    (MAX_TABLE.MAX_SIZE- ED.SIZE_OF_COLONY) YEAR_DEV, 
    ED.ID
FROM ECOLI_DATA ED
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) MAX_TABLE
    ON  YEAR(ED.DIFFERENTIATION_DATE) = MAX_TABLE.YEAR
ORDER BY
    YEAR(ED.DIFFERENTIATION_DATE) ASC, 
    (MAX_TABLE.MAX_SIZE- ED.SIZE_OF_COLONY) ASC